"""
package_exporter.py — Evidence package ZIP export

Assembles a self-contained, verifiable evidence package as a ZIP archive.

Package structure:
  evidence_package_<date>_<short>/
  ├── original/
  │   └── <file_name>          ← copy of the original work file (if found)
  ├── evidence/
  │   └── evidence_<short>.json
  ├── reports/
  │   ├── proof_report_<short>.md
  │   └── proof_report_<short>.pdf
  ├── verification/
  │   ├── verification_guide.md
  │   └── verification_commands.txt
  ├── manifest.json
  └── README.md
"""

import json
import shutil
import zipfile
from datetime import datetime, timezone
from pathlib import Path

from proof_client.config import ENCRYPTED_DIR, EVIDENCE_DIR, REPORTS_DIR, WORKS_DIR
from proof_client.evidence_schema import EvidenceRecord
from proof_client.evidence_store import load_evidence, list_all_evidence
from proof_client.generate_report import generate_report as generate_md_report
from proof_client.ipfs_client import build_ipfs_metadata, gateway_urls
from proof_client.manifest import write_manifest
from proof_client.pdf_report import generate_pdf
from proof_client.report_template import build_markdown_certificate
from proof_client.verification_guide import write_verification_guide


def _package_name(record: EvidenceRecord) -> str:
    """Build the top-level directory name for a package."""
    date_str = datetime.now(timezone.utc).strftime("%Y%m%d")
    short = record.file_hash.replace("0x", "")[:8]
    return f"evidence_package_{date_str}_{short}"


def _readme_content(record: EvidenceRecord, pkg_name: str) -> str:
    """Return README.md content for the evidence package."""
    now_utc = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    short = record.file_hash.replace("0x", "")[:8]
    enc_rows = ""
    enc_block = ""
    if record.has_encrypted_ipfs:
        enc_rows = (
            "| `encrypted/encrypted_file.enc` | AES-256-GCM ciphertext uploaded to IPFS |\n"
            "| `encrypted/encryption_metadata.json` | Public salt/nonce/KDF params (no password) |\n"
        )
        enc_block = f"""
## Encrypted Off-Chain Storage

This file was encrypted locally **before** upload, so public IPFS only stores
ciphertext. The on-chain hash still anchors the original file.

- **Encryption:** {record.encryption_algorithm} · {record.encryption_kdf} ({record.encryption_kdf_iterations} iters)
- **Encrypted IPFS URI:** `{record.encrypted_ipfs_uri}`
- **Encrypted file SHA-256:** `{record.encrypted_file_hash}`

```bash
# Download ciphertext, decrypt, and confirm the original hash
python -m proof_client.verify_encrypted_ipfs --hash {record.file_hash}
```

> The password is **not** stored in this package. It must be supplied by the
> owner out-of-band. If the password is lost, the file cannot be recovered.
"""
    ipfs_rows = ""
    ipfs_block = ""
    if record.has_ipfs:
        ipfs_rows = (
            "| `ipfs/ipfs_metadata.json` | IPFS CID, URI and gateway metadata |\n"
            "| `ipfs/ipfs_gateway_links.txt` | Browsable IPFS gateway links |\n"
        )
        ipfs_block = f"""
## Off-Chain Storage (IPFS)

- **CID:** `{record.ipfs_cid}`
- **URI:** `{record.ipfs_uri}`
- **Gateway:** {record.ipfs_gateway_url}

```bash
# Download from IPFS and confirm the SHA-256 matches
python -m proof_client.verify_ipfs --cid {record.ipfs_cid} --expected-hash {record.file_hash}
```
"""
    return f"""# Evidence Package

**Package name:** {pkg_name}
**Generated at:** {now_utc}
**Purpose:** Proof-of-existence evidence for `{record.file_name}`

---

## Contents

| Path | Description |
|------|-------------|
| `original/{record.file_name}` | Original work file |
| `evidence/evidence_{short}.json` | Machine-readable on-chain evidence record |
| `reports/proof_report_{short}.md` | Human-readable Markdown certificate |
| `reports/proof_report_{short}.pdf` | Human-readable PDF certificate |
| `verification/verification_guide.md` | Step-by-step third-party verification guide |
| `verification/verification_commands.txt` | Copy-pasteable verification commands |
{enc_rows}{ipfs_rows}| `manifest.json` | SHA-256 checksums for all files |
| `README.md` | This file |

---
{enc_block}{ipfs_block}
## Quick Verification

```bash
# 1. Verify evidence package integrity
python -m proof_client.verify_package {pkg_name}.zip

# 2. Recompute file fingerprint
shasum -a 256 original/{record.file_name}
# Expected: {record.file_hash}
```

## Network

- **Blockchain:** {record.network} (Chain ID {record.chain_id})
- **Contract:** `{record.contract_address}`
- **Transaction:** `0x{record.tx_hash}`
- **Block:** {record.block_number} ({record.timestamp_utc})

---

*Generated by proof_client*
"""


def build_encryption_metadata(record: EvidenceRecord) -> dict:
    """Build the dict written to ``encrypted/encryption_metadata.json``.

    Carries only PUBLIC parameters — salt, nonce, KDF settings and hashes.
    The password and key are never included.
    """
    return {
        "algorithm": record.encryption_algorithm,
        "kdf": record.encryption_kdf,
        "kdf_iterations": record.encryption_kdf_iterations,
        "salt_hex": record.encryption_salt_hex,
        "nonce_hex": record.encryption_nonce_hex,
        "original_sha256": record.file_hash,
        "encrypted_sha256": record.encrypted_file_hash,
        "encrypted_file_name": record.encrypted_file_name,
        "encrypted_ipfs_cid": record.encrypted_ipfs_cid,
        "encrypted_ipfs_uri": record.encrypted_ipfs_uri,
        "encrypted_at_utc": record.encrypted_ipfs_uploaded_at,
    }


def _write_encrypted_section(record: EvidenceRecord, enc_dir: Path) -> Path:
    """
    Write encrypted/encryption_metadata.json and, when available, a copy of the
    ciphertext (encrypted_file.enc) for a record that stores encrypted IPFS
    content. The password/key is NEVER written.
    """
    enc_dir.mkdir(parents=True, exist_ok=True)

    metadata = build_encryption_metadata(record)
    (enc_dir / "encryption_metadata.json").write_text(
        json.dumps(metadata, indent=2, ensure_ascii=False), encoding="utf-8"
    )

    # Copy the ciphertext if it is still present locally.
    enc_src = ENCRYPTED_DIR / record.encrypted_file_name if record.encrypted_file_name else None
    dest = enc_dir / "encrypted_file.enc"
    if enc_src and enc_src.exists():
        shutil.copy2(enc_src, dest)
    else:
        dest.write_text(
            "[Encrypted file not found locally at packaging time]\n"
            f"Encrypted SHA-256: {record.encrypted_file_hash}\n"
            f"Re-download from IPFS: {record.encrypted_ipfs_uri}\n",
            encoding="utf-8",
        )
    return enc_dir


def _write_ipfs_section(record: EvidenceRecord, ipfs_dir: Path) -> Path:
    """
    Write ipfs/ipfs_metadata.json and ipfs/ipfs_gateway_links.txt for a record
    that carries an IPFS CID.
    """
    ipfs_dir.mkdir(parents=True, exist_ok=True)

    metadata = build_ipfs_metadata(record)
    (ipfs_dir / "ipfs_metadata.json").write_text(
        json.dumps(metadata, indent=2, ensure_ascii=False), encoding="utf-8"
    )

    links = [
        f"# IPFS gateway links for CID {record.ipfs_cid}",
        f"# URI: {record.ipfs_uri}",
        "",
        *gateway_urls(record.ipfs_cid),
        "",
    ]
    (ipfs_dir / "ipfs_gateway_links.txt").write_text(
        "\n".join(links), encoding="utf-8"
    )
    return ipfs_dir


def _default_include_original(record: EvidenceRecord) -> bool:
    """Default policy: exclude the plaintext original for encrypted records.

    Stage 8 packages are privacy-aware. When a file was encrypted before
    upload, including the plaintext in the package would defeat the purpose,
    so the default is to exclude it. Plain (non-encrypted) records keep the
    pre-Stage-8 behaviour of including the original.
    """
    return not record.is_encrypted


def build_package(
    record: EvidenceRecord,
    output_dir: Path,
    include_original: bool | None = None,
) -> Path:
    """
    Build an evidence package directory for a single record.

    Args:
        record: EvidenceRecord to package.
        output_dir: Directory where the package folder will be created.
        include_original: Whether to bundle the plaintext original. When None,
            defaults to excluding it for encrypted records and including it
            otherwise.

    Returns:
        Path to the created package directory.
    """
    if include_original is None:
        include_original = _default_include_original(record)

    pkg_name = _package_name(record)
    pkg_dir = output_dir / pkg_name
    pkg_dir.mkdir(parents=True, exist_ok=True)

    short = record.file_hash.replace("0x", "")[:8]

    # ── original/ ────────────────────────────────────────────────
    orig_dir = pkg_dir / "original"
    orig_dir.mkdir(exist_ok=True)
    orig_src = WORKS_DIR / record.file_name
    if not include_original:
        # Privacy-aware: omit the plaintext, leave an explanatory note.
        (orig_dir / "README.md").write_text(
            "# Original File Not Included\n\n"
            "The original file is **not** included in this encrypted evidence "
            "package. Only encrypted content and verification metadata are "
            "included.\n\n"
            f"- **Original SHA-256:** `{record.file_hash}`\n"
            f"- **Encrypted IPFS URI:** `{record.encrypted_ipfs_uri}`\n\n"
            "To recover the original, download the ciphertext from IPFS and "
            "decrypt it with the owner-supplied password "
            "(see `verification/verification_guide.md`, Step 5).\n",
            encoding="utf-8",
        )
    elif orig_src.exists():
        shutil.copy2(orig_src, orig_dir / record.file_name)
    else:
        # Create a placeholder if the original is not found
        (orig_dir / record.file_name).write_text(
            f"[Original file not found at time of packaging]\n"
            f"SHA-256: {record.file_hash}\n",
            encoding="utf-8",
        )

    # ── evidence/ ────────────────────────────────────────────────
    ev_dir = pkg_dir / "evidence"
    ev_dir.mkdir(exist_ok=True)
    ev_src = EVIDENCE_DIR / f"evidence_{short}.json"
    if ev_src.exists():
        shutil.copy2(ev_src, ev_dir / f"evidence_{short}.json")

    # ── reports/ ─────────────────────────────────────────────────
    rep_dir = pkg_dir / "reports"
    rep_dir.mkdir(exist_ok=True)

    md_path = generate_md_report(record.file_hash)
    if md_path and md_path.exists():
        shutil.copy2(md_path, rep_dir / md_path.name)

    # Generate PDF (manifest_hash added later; pass empty string for now)
    pdf_path = generate_pdf(record)
    if pdf_path and pdf_path.exists():
        shutil.copy2(pdf_path, rep_dir / pdf_path.name)

    # ── verification/ ────────────────────────────────────────────
    ver_dir = pkg_dir / "verification"
    write_verification_guide(record, ver_dir)

    # ── ipfs/ (only when the record carries a CID) ───────────────
    if record.has_ipfs:
        _write_ipfs_section(record, pkg_dir / "ipfs")

    # ── encrypted/ (only when the record stores encrypted content) ─
    if record.has_encrypted_ipfs:
        _write_encrypted_section(record, pkg_dir / "encrypted")

    # ── manifest.json ────────────────────────────────────────────
    _, manifest_hash = write_manifest(pkg_dir)

    # ── README.md ────────────────────────────────────────────────
    (pkg_dir / "README.md").write_text(
        _readme_content(record, pkg_name), encoding="utf-8"
    )

    # Re-generate PDF with manifest_hash now known, then update manifest
    updated_pdf = generate_pdf(record, manifest_hash)
    if updated_pdf and updated_pdf.exists():
        dest = rep_dir / updated_pdf.name
        shutil.copy2(updated_pdf, dest)

    # Rewrite manifest after README.md and updated PDF
    write_manifest(pkg_dir)

    return pkg_dir


def zip_package(pkg_dir: Path, output_dir: Path) -> Path:
    """
    Create a ZIP archive of a package directory.

    Args:
        pkg_dir: Package directory to compress.
        output_dir: Directory where the ZIP will be written.

    Returns:
        Path to the created ZIP file.
    """
    zip_path = output_dir / f"{pkg_dir.name}.zip"
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
        for file_path in sorted(pkg_dir.rglob("*")):
            if file_path.is_file():
                arcname = file_path.relative_to(output_dir)
                zf.write(file_path, arcname)
    return zip_path


def export_package(
    record: EvidenceRecord,
    output_dir: Path,
    include_original: bool | None = None,
) -> tuple[Path, Path]:
    """
    Build a package directory and compress it to ZIP.

    Args:
        record: EvidenceRecord to export.
        output_dir: Directory where the package and ZIP will be written.
        include_original: Whether to bundle the plaintext original (see
            build_package). None uses the privacy-aware default.

    Returns:
        (package_dir, zip_path)
    """
    output_dir.mkdir(parents=True, exist_ok=True)
    pkg_dir = build_package(record, output_dir, include_original=include_original)
    zip_path = zip_package(pkg_dir, output_dir)

    print(f"📦 Package: {pkg_dir}")
    print(f"🗜️  ZIP:     {zip_path}")
    return pkg_dir, zip_path


def export_by_hash(
    file_hash: str, output_dir: Path, include_original: bool | None = None
) -> tuple[Path, Path] | None:
    """Export a package for a single file hash."""
    record = load_evidence(file_hash)
    if record is None:
        print(f"❌ No evidence found for hash {file_hash}")
        return None
    return export_package(record, output_dir, include_original=include_original)


def export_all(
    output_dir: Path, include_original: bool | None = None
) -> list[tuple[Path, Path]]:
    """Export packages for all existing evidence records."""
    records = list_all_evidence()
    if not records:
        print("⚠️  No evidence records found.")
        return []
    results = []
    for record in records:
        result = export_package(record, output_dir, include_original=include_original)
        results.append(result)
    print(f"\n✅ Exported {len(results)} package(s) to {output_dir}")
    return results
